var jobElements = function () {
    this.customerNameElement=element(by.id('tblCustomerName1'));
    this.filterStatus='filterStatus_chosen';
    this.filterStatusDropdown=element(by.id('filterStatusDropdown'));
    this.deliveredStatus='Delivered';
    this.newStatus='New';
    this.quotingStatus='Quoting';
    this.statusElement=element(by.id('tblStatus1'));
    this.txtSearchCustomer = element(by.id('searchCustomers'));
    this.repeaterJobList = 'jobObj in planning.jobList';
    this.repeaterJobs = 'jobObj in job.jobList';
    this.columnVehicleSize = 'vehicleSize';
    this.columnPalletQuantity = 'palletQty';
    this.btnNewJob = element(by.id("btn-top-search"));
    this.txtSearchJobs = element(by.id('plannerDateInput'));
    this.customerChosen = "customer_chosen";
    this.txtVehicleSize = element(by.xpath("//input[@name='vehicleSize']"));
    this.txtVehicleType = element(by.xpath("//input[@name='vehicleType']"));
    this.txtPalletQty = element(by.id("palletQty"));
    this.noTailLiftRadio = element(by.id("noTailLiftRadio"));
    this.txtWeight = element(by.name("weight"));
    this.txtnoAdrRadio= element(by.id("noAdrRadio"));
    this.collectionPointChosen= "collectionPoint_chosen";
    this.txtcollectionDateTime= element(by.id("collectionDateTime"));
    this.deliveryPointChosen= "deliveryPoint_chosen";
    this.txtdeliveryDateTime= element(by.id("deliveryDateTime"));
    this.txtpriceQuoted= element(by.id("priceQuoted"));
    this.txtcomments= element(by.id("comments"));
    this.btnSaveJob= element(by.id("btnSaveJob"));
    this.btnCancelJob= element(by.id("btnCancelJob"));
    this.tblJobRow = element(by.id("tblCustomerName1"));
    this.acceptQuote1 = element(by.id("acceptQuote1"));
    this.deliveryPointAddbtn = element(by.id("deliveryPointAddbtn"));
    this.name = element(by.id("name"));
    this.address = element(by.id("address"));
    this.town = element(by.id("town"));
    this.county = element(by.id("county"));
    this.postcode = element(by.id("postcode"));
    this.contact = element(by.id("contact"));
    this.telephone = element(by.id("telephone"));
    this.btnSaveCollection = element(by.id("btnSaveCollection"));
    this.btnExpiryDate = element(by.id("btnExpiryDate"));
    this.collectionDateTimeHeader="collectionDateTimeHeader";
    this.deliveryDateHeader="deliveryDateHeader";
    this.tblCollectionDateTime1=element(by.id("tblCollectionDateTime1"));
    this.tblDeliveryDateTime1=element(by.id("tblDeliveryDateTime1"));
    this.unacceptQuote1 = element(by.id("unacceptQuote1"));
    
    
};
module.exports = new jobElements();
